# Copyright IBM Corp. 2014, 2026
# SPDX-License-Identifier: MPL-2.0

version: "2"
linters:
  default: none
  enable:
    - dupl
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    revive:
      severity: warning
      rules:
        - name: package-comments
          severity: warning
          disabled: true
        - name: exported
          arguments:
            - checkPrivateReceivers
            - disableStutteringCheck
          severity: warning
          disabled: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
