language: go

script:
  - go test -v -covermode=count -coverprofile=coverage.out ./...

after_script:
  # Install and upload test coverage must not failure for test build
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

