name: build

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - "oldstable"
          - "stable"

    steps:
      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Build, test and generate coverage report
        run: |
          go test -timeout=60s -race -v ./... -coverprofile=coverage.out
          go build -race ./...

      - name: Build and test ARC
        working-directory: ./arc
        run: |
          go test -timeout=60s -race
          go build -race

      - name: Upload the coverage report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
         path: coverage.out
         name: Coverage-report

      - name: Display the coverage report
        run: go tool cover -func=coverage.out

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0

      - name: Run golangci-lint on ARC
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          working-directory: ./arc
