name: build

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - "oldstable"
          - "stable"

    steps:
      - name: Setup Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Build, test and generate coverage report
        run: |
          go test -timeout=60s -race -v ./... -coverprofile=coverage.out
          go build -race ./...

      - name: Build and test ARC
        working-directory: ./arc
        run: |
          go test -timeout=60s -race
          go build -race

      - name: Upload the coverage report
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
         path: coverage.out
         name: Coverage-report

      - name: Display the coverage report
        run: go tool cover -func=coverage.out

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0

      - name: Run golangci-lint on ARC
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          working-directory: ./arc
